name: "Your name here"
description: "Provide a description here"
author: "Your name or organization here"
inputs:
  current-tag:
    required: true
    description: ""
  tag-pattern:
    required: false
    description: "Tag naming convention."
    default: ""
  kind:
    required: false
    description: 'Decide what style you would like to use. Now the action has "default"'
    default: "default"
  scopes:
    required: false
    description: "Scopes you would like to include"
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
