name: "build-test"
on:
  push:
    tags:
      - "test-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: gen_note
        with:
          style: angular
      - name: Print the release note
        run: echo "${{ steps.gen_note.outputs.summary }}"
