name: "build-test"
on:
  push:
    tags:
      - "test-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generated content
        uses: ./
        id: gen_note
        with:
          kind: default
          tagPattern: v*
          currentTag: ${{ github.ref_name }}
      - name: Print the release note
        run: echo "${{ steps.gen_note.outputs.summary }}"
